channels:
  - conda-forge
dependencies:
  - python >=3.7.1,<3.10
  - pip >=21.3.1
  - numpy >=1.21.2,<1.22.4
  - matplotlib >=3.4.2,<3.6.0
  - geopandas >=0.10.2
  - gdal >=3.3.3,<3.5.1
  - pyramids >=0.1.1
  - pip:
      - loguru >=0.5.3
      - statista >=0.1.0
      - geoplot >=0.5.1
      - pytest >=6.2.5
      - pytest-cov >=2.12.1
